# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and Test

on:
  push:
    branches: [ master ]
    paths:
    - 'bcpandas/**'
    - './github/workflows/*.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'bcpandas/**'

jobs:
  build:
    env:
      CONDA_ENV_NAME: bcpandas-env
    runs-on: ${{ matrix.os }}
    # continue-on-error: false
    strategy:
      fail-fast: true
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
       auto-update-conda: true
       activate-environment: ${{ env.CONDA_ENV_NAME }}
       environment-file: env.yml
       python-version: ${{ matrix.python-version }}
       auto-activate-base: false
    - name: Lint with flake8 and check with mypy (on Linux)
      if: ${{ runner.os == 'Linux'}}
      # per https://github.com/goanpeca/setup-miniconda#important
      shell: bash -l {0}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --statistics --select=E9,F63,F7,F82 --show-source 
        # regular flake8 check
        flake8 . --count --statistics
        mypy .
    - name: Lint with flake8 and check with mypy (on Windows)
      if: ${{ runner.os == 'Windows'}}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --statistics --select=E9,F63,F7,F82 --show-source 
        # regular flake8 check
        flake8 . --count --statistics
        mypy .
    - name: Install BCP Utility (on Linux)
      if: ${{ runner.os == 'Linux'}}
      run: |
        # https://docs.microsoft.com/en-us/sql/linux/sql-server-linux-setup-tools?view=sql-server-ver15#ubuntu
        curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
        sudo apt-get update 
        sudo apt-get install mssql-tools unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc
    - name: Test BCP
      run: bcp -v
    - name: Prepare Docker image for testing (Linux)
      if: ${{ runner.os == 'Linux'}}
      run: docker pull mcr.microsoft.com/mssql/server:2017-latest
    - name: Prepare Docker image for testing (Windows)
      if: ${{ runner.os == 'Windows'}}
      run: docker pull microsoft/mssql-server-windows-express:2016
    - name: Test with pytest (on Linux)
      if: ${{ runner.os == 'Linux'}}
      shell: bash -l {0}
      run: |
        pytest --mssql-docker-image mcr.microsoft.com/mssql/server:2017-latest bcpandas/tests/test_to_sql.py
    - name: Test with pytest (on Windows)
      if: ${{ runner.os == 'Windows'}}
      run: |
        pytest --mssql-docker-image microsoft/mssql-server-windows-express:2016 bcpandas/tests/test_to_sql.py
