# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docker testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - name: Docker debug
      shell: powershell
      run: |
        docker version
        # & $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchLinuxEngine
    - name: find dockercli.exe
      shell: cmd
      run: |
        dir C:\*DockerCli.exe /s
