# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CONDA_ENV_NAME: bcpandas-env
    runs-on: [windows-latest]
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: goanpeca/setup-miniconda@v1
      with:
       auto-update-conda: true
       activate-environment: ${{ env.CONDA_ENV_NAME }}
       environment-file: env.yml
       python-version: ${{ matrix.python-version }}
       auto-activate-base: false
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --statistics --select=E9,F63,F7,F82 --show-source 
        # regular flake8 check
        flake8 . --count --statistics
    - name: Mypy check
      run: mypy .
    - name: Switch Docker to Linux containers
      shell: powershell
      run: |
        # https://forums.docker.com/t/cli-to-switch-between-linux-and-windows-images/30297
        # https://stackoverflow.com/a/3593445/6067848
        & $Env:ProgramFiles\Docker\Docker\DockerCli.exe -SwitchLinuxEngine
    - name: Prepare Docker image for testing
      run: docker pull mcr.microsoft.com/mssql/server:2017-latest
    - name: Test with pytest
      run: |
        pytest bcpandas/tests
