# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      CONDA_ENV_NAME: bcpandas-test-env
    runs-on: [windows-latest]
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      shell: powershell
      run: $ENV:CONDA create -n $ENV:CONDA_ENV_NAME python=${{ matrix.python-version }} -y -v
    - name: Set up Conda and packages
      shell: powershell
      run: |
        $ENV:CONDA info -a
        $ENV:CONDA list
        $ENV:CONDA update conda
        $ENV:CONDA env update -n $ENV:CONDA_ENV_NAME -f env.yml
    - name: Show Conda env stuff
      shell: powershell
      run: |
        $ENV:CONDA info -a
        $ENV:CONDA list
        $ENV:CONDA list -n $ENV:CONDA_ENV_NAME
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest -h
